language: ruby
rvm:
- 1.9.3
env:
- DB=sqlite
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake spec
- RAILS_ENV=test bundle exec rake cucumber
notifications:
  slack:
    secure: B6DA4MSbt69bvBTMoIjfuL+Itl4qlCqRqevGrs3nMHPXoro1EAvAcdGi7mTlkmRu/Zc9dFXokDHvVA8Rtgg6nnfF7IgL7XyBkKdPssN7QOBJpU/7v7UulN6RjZwdWL5EXQhJODJLCExYBMqNQOWJ/qCISozmsY4MvkZdBQ3utBM=
sudo: false