default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: smidig_development

test: &test
  <<: *default
  database: smidig_test

production:
  <<: *default
  database: smidig_production
  username: smidig
  password: <%= ENV['SMIDIG_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
