s3: &s3
  storage: s3
  s3_credentials: <%= Rails.root %>/config/s3.yml
  path: ':id-:filename'

test:
  storage: filesystem

development:
  storage: filesystem

staging:
  <<: *s3

production:
  <<: *s3