development: &development
  paypal_email:         ivarconr@gmail.com
  paypal_url:           "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_validate_url:  "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_notify-validate"

test:
  paypal_email:         paypal@smidig.no
  paypal_url:           "https://www.paypal.com/cgi-bin/webscr"
  paypal_validate_url:  "https://www.paypal.com/cgi-bin/webscr?cmd=_notify-validate"

staging:
  paypal_email:         paypal@smidig.no
  paypal_url:           "https://www.paypal.com/cgi-bin/webscr"
  paypal_validate_url:  "https://www.paypal.com/cgi-bin/webscr?cmd=_notify-validate"

production: &production
  paypal_email:         paypal@smidig.no
  paypal_url:           "https://www.paypal.com/cgi-bin/webscr"
  paypal_validate_url:  "https://www.paypal.com/cgi-bin/webscr?cmd=_notify-validate"

